global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "mongodb-sniffer"
    static_configs:
      - targets:
        - "percona_mongodb_exporter:9216"
  - job_name: watchtower
    scrape_interval: 5s
    metrics_path: /v1/metrics
    bearer_token: demotoken
    static_configs:
      - targets:
        - 'watchtower:8080'
