services:
  mongo1:
    image: mongo:5
    container_name: mongo1
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo1
    networks:
      - mongoCluster

    ports:
      - "27017:27017"
  volumes:
      - ./mongo1_data:/data/db
  mongo2:
    image: mongo:5
    container_name: mongo2
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo2
    networks:
      - mongoCluster
    volumes:
      - ./mongo2_data:/data/db
    ports:
      - "27018:27017"

  mongo3:
    image: mongo:5
    container_name: mongo3
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo3
    networks:
      - mongoCluster
    volumes:
      - ./mongo3_data:/data/db
    ports:
      - "27019:27017"
volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
networks:
  mongoCluster:
    driver: bridge

