name: Publicar imagenes


on:
  push:
    branches: ['main']


jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./TP-FINAL-Mio/backend
          file: ./TP-FINAL-Mio/backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/backendhia:latest
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./TP-FINAL-Mio/frontend
          file: ./TP-FINAL-Mio/frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/frontendhia:latest
